# Generated by Django 4.2.9 on 2024-01-30 22:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Metrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_date", models.DateField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "metrics",
            },
        ),
        migrations.CreateModel(
            name="Departments",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("functions", models.CharField(max_length=200)),
                ("new", models.CharField(max_length=200)),
                ("retained", models.CharField(max_length=200)),
                ("churned", models.CharField(max_length=200)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="core.metrics",
                    ),
                ),
            ],
            options={
                "db_table": "departments",
            },
        ),
    ]
