# Generated by Django 4.2.9 on 2024-01-31 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_departments_churned_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departments",
            name="metric",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="core.metrics",
            ),
        ),
    ]
